# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vagrant/projects/try-workflow

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vagrant/projects/try-workflow

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vagrant/projects/try-workflow/CMakeFiles /home/vagrant/projects/try-workflow/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vagrant/projects/try-workflow/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zeek_agent_tests

# Build rule for target.
zeek_agent_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_agent_tests
.PHONY : zeek_agent_tests

# fast build rule for target.
zeek_agent_tests/fast:
	$(MAKE) -f CMakeFiles/zeek_agent_tests.dir/build.make CMakeFiles/zeek_agent_tests.dir/build
.PHONY : zeek_agent_tests/fast

#=============================================================================
# Target rules for targets named zeek-agent_tests

# Build rule for target.
zeek-agent_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek-agent_tests
.PHONY : zeek-agent_tests

# fast build rule for target.
zeek-agent_tests/fast:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/build
.PHONY : zeek-agent_tests/fast

#=============================================================================
# Target rules for targets named zeek-agent_tests_runner

# Build rule for target.
zeek-agent_tests_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek-agent_tests_runner
.PHONY : zeek-agent_tests_runner

# fast build rule for target.
zeek-agent_tests_runner/fast:
	$(MAKE) -f CMakeFiles/zeek-agent_tests_runner.dir/build.make CMakeFiles/zeek-agent_tests_runner.dir/build
.PHONY : zeek-agent_tests_runner/fast

#=============================================================================
# Target rules for targets named zeek-agent

# Build rule for target.
zeek-agent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek-agent
.PHONY : zeek-agent

# fast build rule for target.
zeek-agent/fast:
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/build
.PHONY : zeek-agent/fast

#=============================================================================
# Target rules for targets named thirdparty_broker

# Build rule for target.
thirdparty_broker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_broker
.PHONY : thirdparty_broker

# fast build rule for target.
thirdparty_broker/fast:
	$(MAKE) -f libraries/broker/CMakeFiles/thirdparty_broker.dir/build.make libraries/broker/CMakeFiles/thirdparty_broker.dir/build
.PHONY : thirdparty_broker/fast

#=============================================================================
# Target rules for targets named thirdparty_caf_openssl

# Build rule for target.
thirdparty_caf_openssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_caf_openssl
.PHONY : thirdparty_caf_openssl

# fast build rule for target.
thirdparty_caf_openssl/fast:
	$(MAKE) -f libraries/broker/CMakeFiles/thirdparty_caf_openssl.dir/build.make libraries/broker/CMakeFiles/thirdparty_caf_openssl.dir/build
.PHONY : thirdparty_caf_openssl/fast

#=============================================================================
# Target rules for targets named thirdparty_caf_io

# Build rule for target.
thirdparty_caf_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_caf_io
.PHONY : thirdparty_caf_io

# fast build rule for target.
thirdparty_caf_io/fast:
	$(MAKE) -f libraries/broker/CMakeFiles/thirdparty_caf_io.dir/build.make libraries/broker/CMakeFiles/thirdparty_caf_io.dir/build
.PHONY : thirdparty_caf_io/fast

#=============================================================================
# Target rules for targets named thirdparty_caf_core

# Build rule for target.
thirdparty_caf_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_caf_core
.PHONY : thirdparty_caf_core

# fast build rule for target.
thirdparty_caf_core/fast:
	$(MAKE) -f libraries/broker/CMakeFiles/thirdparty_caf_core.dir/build.make libraries/broker/CMakeFiles/thirdparty_caf_core.dir/build
.PHONY : thirdparty_caf_core/fast

#=============================================================================
# Target rules for targets named thirdparty_audit_libauparse

# Build rule for target.
thirdparty_audit_libauparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_audit_libauparse
.PHONY : thirdparty_audit_libauparse

# fast build rule for target.
thirdparty_audit_libauparse/fast:
	$(MAKE) -f libraries/audit/CMakeFiles/thirdparty_audit_libauparse.dir/build.make libraries/audit/CMakeFiles/thirdparty_audit_libauparse.dir/build
.PHONY : thirdparty_audit_libauparse/fast

#=============================================================================
# Target rules for targets named thirdparty_audit_libaudit

# Build rule for target.
thirdparty_audit_libaudit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_audit_libaudit
.PHONY : thirdparty_audit_libaudit

# fast build rule for target.
thirdparty_audit_libaudit/fast:
	$(MAKE) -f libraries/audit/CMakeFiles/thirdparty_audit_libaudit.dir/build.make libraries/audit/CMakeFiles/thirdparty_audit_libaudit.dir/build
.PHONY : thirdparty_audit_libaudit/fast

#=============================================================================
# Target rules for targets named thirdparty_xxhash

# Build rule for target.
thirdparty_xxhash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_xxhash
.PHONY : thirdparty_xxhash

# fast build rule for target.
thirdparty_xxhash/fast:
	$(MAKE) -f libraries/xxhash/CMakeFiles/thirdparty_xxhash.dir/build.make libraries/xxhash/CMakeFiles/thirdparty_xxhash.dir/build
.PHONY : thirdparty_xxhash/fast

#=============================================================================
# Target rules for targets named thirdparty_sqlite

# Build rule for target.
thirdparty_sqlite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_sqlite
.PHONY : thirdparty_sqlite

# fast build rule for target.
thirdparty_sqlite/fast:
	$(MAKE) -f libraries/sqlite/src/CMakeFiles/thirdparty_sqlite.dir/build.make libraries/sqlite/src/CMakeFiles/thirdparty_sqlite.dir/build
.PHONY : thirdparty_sqlite/fast

#=============================================================================
# Target rules for targets named thirdparty_zlib

# Build rule for target.
thirdparty_zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_zlib
.PHONY : thirdparty_zlib

# fast build rule for target.
thirdparty_zlib/fast:
	$(MAKE) -f libraries/zlib/CMakeFiles/thirdparty_zlib.dir/build.make libraries/zlib/CMakeFiles/thirdparty_zlib.dir/build
.PHONY : thirdparty_zlib/fast

#=============================================================================
# Target rules for targets named thirdparty_openssl_builder

# Build rule for target.
thirdparty_openssl_builder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thirdparty_openssl_builder
.PHONY : thirdparty_openssl_builder

# fast build rule for target.
thirdparty_openssl_builder/fast:
	$(MAKE) -f libraries/openssl/CMakeFiles/thirdparty_openssl_builder.dir/build.make libraries/openssl/CMakeFiles/thirdparty_openssl_builder.dir/build
.PHONY : thirdparty_openssl_builder/fast

#=============================================================================
# Target rules for targets named zeek_utils

# Build rule for target.
zeek_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_utils
.PHONY : zeek_utils

# fast build rule for target.
zeek_utils/fast:
	$(MAKE) -f components/zeekutils/CMakeFiles/zeek_utils.dir/build.make components/zeekutils/CMakeFiles/zeek_utils.dir/build
.PHONY : zeek_utils/fast

#=============================================================================
# Target rules for targets named zeek_database_tests_runner

# Build rule for target.
zeek_database_tests_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_database_tests_runner
.PHONY : zeek_database_tests_runner

# fast build rule for target.
zeek_database_tests_runner/fast:
	$(MAKE) -f components/zeekdatabase/CMakeFiles/zeek_database_tests_runner.dir/build.make components/zeekdatabase/CMakeFiles/zeek_database_tests_runner.dir/build
.PHONY : zeek_database_tests_runner/fast

#=============================================================================
# Target rules for targets named zeek_database_tests

# Build rule for target.
zeek_database_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_database_tests
.PHONY : zeek_database_tests

# fast build rule for target.
zeek_database_tests/fast:
	$(MAKE) -f components/zeekdatabase/CMakeFiles/zeek_database_tests.dir/build.make components/zeekdatabase/CMakeFiles/zeek_database_tests.dir/build
.PHONY : zeek_database_tests/fast

#=============================================================================
# Target rules for targets named zeek_database

# Build rule for target.
zeek_database: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_database
.PHONY : zeek_database

# fast build rule for target.
zeek_database/fast:
	$(MAKE) -f components/zeekdatabase/CMakeFiles/zeek_database.dir/build.make components/zeekdatabase/CMakeFiles/zeek_database.dir/build
.PHONY : zeek_database/fast

#=============================================================================
# Target rules for targets named zeek_logger

# Build rule for target.
zeek_logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_logger
.PHONY : zeek_logger

# fast build rule for target.
zeek_logger/fast:
	$(MAKE) -f components/zeeklogger/CMakeFiles/zeek_logger.dir/build.make components/zeeklogger/CMakeFiles/zeek_logger.dir/build
.PHONY : zeek_logger/fast

#=============================================================================
# Target rules for targets named zeek_service_manager

# Build rule for target.
zeek_service_manager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_service_manager
.PHONY : zeek_service_manager

# fast build rule for target.
zeek_service_manager/fast:
	$(MAKE) -f components/zeekservicemanager/CMakeFiles/zeek_service_manager.dir/build.make components/zeekservicemanager/CMakeFiles/zeek_service_manager.dir/build
.PHONY : zeek_service_manager/fast

#=============================================================================
# Target rules for targets named zeek_configuration_tests_runner

# Build rule for target.
zeek_configuration_tests_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_configuration_tests_runner
.PHONY : zeek_configuration_tests_runner

# fast build rule for target.
zeek_configuration_tests_runner/fast:
	$(MAKE) -f components/zeekconfiguration/CMakeFiles/zeek_configuration_tests_runner.dir/build.make components/zeekconfiguration/CMakeFiles/zeek_configuration_tests_runner.dir/build
.PHONY : zeek_configuration_tests_runner/fast

#=============================================================================
# Target rules for targets named zeek_configuration_tests

# Build rule for target.
zeek_configuration_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_configuration_tests
.PHONY : zeek_configuration_tests

# fast build rule for target.
zeek_configuration_tests/fast:
	$(MAKE) -f components/zeekconfiguration/CMakeFiles/zeek_configuration_tests.dir/build.make components/zeekconfiguration/CMakeFiles/zeek_configuration_tests.dir/build
.PHONY : zeek_configuration_tests/fast

#=============================================================================
# Target rules for targets named zeek_configuration

# Build rule for target.
zeek_configuration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_configuration
.PHONY : zeek_configuration

# fast build rule for target.
zeek_configuration/fast:
	$(MAKE) -f components/zeekconfiguration/CMakeFiles/zeek_configuration.dir/build.make components/zeekconfiguration/CMakeFiles/zeek_configuration.dir/build
.PHONY : zeek_configuration/fast

#=============================================================================
# Target rules for targets named zeek_audisp_tests_runner

# Build rule for target.
zeek_audisp_tests_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_audisp_tests_runner
.PHONY : zeek_audisp_tests_runner

# fast build rule for target.
zeek_audisp_tests_runner/fast:
	$(MAKE) -f components/zeekaudisp/CMakeFiles/zeek_audisp_tests_runner.dir/build.make components/zeekaudisp/CMakeFiles/zeek_audisp_tests_runner.dir/build
.PHONY : zeek_audisp_tests_runner/fast

#=============================================================================
# Target rules for targets named zeek_audisp_tests

# Build rule for target.
zeek_audisp_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_audisp_tests
.PHONY : zeek_audisp_tests

# fast build rule for target.
zeek_audisp_tests/fast:
	$(MAKE) -f components/zeekaudisp/CMakeFiles/zeek_audisp_tests.dir/build.make components/zeekaudisp/CMakeFiles/zeek_audisp_tests.dir/build
.PHONY : zeek_audisp_tests/fast

#=============================================================================
# Target rules for targets named zeek_audisp

# Build rule for target.
zeek_audisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_audisp
.PHONY : zeek_audisp

# fast build rule for target.
zeek_audisp/fast:
	$(MAKE) -f components/zeekaudisp/CMakeFiles/zeek_audisp.dir/build.make components/zeekaudisp/CMakeFiles/zeek_audisp.dir/build
.PHONY : zeek_audisp/fast

#=============================================================================
# Target rules for targets named zeek_audisp_tables_tests_runner

# Build rule for target.
zeek_audisp_tables_tests_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_audisp_tables_tests_runner
.PHONY : zeek_audisp_tables_tests_runner

# fast build rule for target.
zeek_audisp_tables_tests_runner/fast:
	$(MAKE) -f tables/audisp/CMakeFiles/zeek_audisp_tables_tests_runner.dir/build.make tables/audisp/CMakeFiles/zeek_audisp_tables_tests_runner.dir/build
.PHONY : zeek_audisp_tables_tests_runner/fast

#=============================================================================
# Target rules for targets named zeek_audisp_tables_tests

# Build rule for target.
zeek_audisp_tables_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_audisp_tables_tests
.PHONY : zeek_audisp_tables_tests

# fast build rule for target.
zeek_audisp_tables_tests/fast:
	$(MAKE) -f tables/audisp/CMakeFiles/zeek_audisp_tables_tests.dir/build.make tables/audisp/CMakeFiles/zeek_audisp_tables_tests.dir/build
.PHONY : zeek_audisp_tables_tests/fast

#=============================================================================
# Target rules for targets named zeek_audisp_tables

# Build rule for target.
zeek_audisp_tables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_audisp_tables
.PHONY : zeek_audisp_tables

# fast build rule for target.
zeek_audisp_tables/fast:
	$(MAKE) -f tables/audisp/CMakeFiles/zeek_audisp_tables.dir/build.make tables/audisp/CMakeFiles/zeek_audisp_tables.dir/build
.PHONY : zeek_audisp_tables/fast

#=============================================================================
# Target rules for targets named zeek_host_information_table

# Build rule for target.
zeek_host_information_table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zeek_host_information_table
.PHONY : zeek_host_information_table

# fast build rule for target.
zeek_host_information_table/fast:
	$(MAKE) -f tables/host_information/CMakeFiles/zeek_host_information_table.dir/build.make tables/host_information/CMakeFiles/zeek_host_information_table.dir/build
.PHONY : zeek_host_information_table/fast

src/configuration.o: src/configuration.cpp.o

.PHONY : src/configuration.o

# target to build an object file
src/configuration.cpp.o:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/configuration.cpp.o
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/configuration.cpp.o
.PHONY : src/configuration.cpp.o

src/configuration.i: src/configuration.cpp.i

.PHONY : src/configuration.i

# target to preprocess a source file
src/configuration.cpp.i:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/configuration.cpp.i
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/configuration.cpp.i
.PHONY : src/configuration.cpp.i

src/configuration.s: src/configuration.cpp.s

.PHONY : src/configuration.s

# target to generate assembly for a file
src/configuration.cpp.s:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/configuration.cpp.s
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/configuration.cpp.s
.PHONY : src/configuration.cpp.s

src/logger.o: src/logger.cpp.o

.PHONY : src/logger.o

# target to build an object file
src/logger.cpp.o:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/logger.cpp.o
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/logger.cpp.o
.PHONY : src/logger.cpp.o

src/logger.i: src/logger.cpp.i

.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cpp.i:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/logger.cpp.i
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/logger.cpp.i
.PHONY : src/logger.cpp.i

src/logger.s: src/logger.cpp.s

.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cpp.s:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/logger.cpp.s
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/logger.cpp.s
.PHONY : src/logger.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/queryscheduler.o: src/queryscheduler.cpp.o

.PHONY : src/queryscheduler.o

# target to build an object file
src/queryscheduler.cpp.o:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/queryscheduler.cpp.o
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/queryscheduler.cpp.o
.PHONY : src/queryscheduler.cpp.o

src/queryscheduler.i: src/queryscheduler.cpp.i

.PHONY : src/queryscheduler.i

# target to preprocess a source file
src/queryscheduler.cpp.i:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/queryscheduler.cpp.i
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/queryscheduler.cpp.i
.PHONY : src/queryscheduler.cpp.i

src/queryscheduler.s: src/queryscheduler.cpp.s

.PHONY : src/queryscheduler.s

# target to generate assembly for a file
src/queryscheduler.cpp.s:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/queryscheduler.cpp.s
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/queryscheduler.cpp.s
.PHONY : src/queryscheduler.cpp.s

src/uniquexxh64state.o: src/uniquexxh64state.cpp.o

.PHONY : src/uniquexxh64state.o

# target to build an object file
src/uniquexxh64state.cpp.o:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/uniquexxh64state.cpp.o
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/uniquexxh64state.cpp.o
.PHONY : src/uniquexxh64state.cpp.o

src/uniquexxh64state.i: src/uniquexxh64state.cpp.i

.PHONY : src/uniquexxh64state.i

# target to preprocess a source file
src/uniquexxh64state.cpp.i:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/uniquexxh64state.cpp.i
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/uniquexxh64state.cpp.i
.PHONY : src/uniquexxh64state.cpp.i

src/uniquexxh64state.s: src/uniquexxh64state.cpp.s

.PHONY : src/uniquexxh64state.s

# target to generate assembly for a file
src/uniquexxh64state.cpp.s:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/uniquexxh64state.cpp.s
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/uniquexxh64state.cpp.s
.PHONY : src/uniquexxh64state.cpp.s

src/zeekagent.o: src/zeekagent.cpp.o

.PHONY : src/zeekagent.o

# target to build an object file
src/zeekagent.cpp.o:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/zeekagent.cpp.o
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/zeekagent.cpp.o
.PHONY : src/zeekagent.cpp.o

src/zeekagent.i: src/zeekagent.cpp.i

.PHONY : src/zeekagent.i

# target to preprocess a source file
src/zeekagent.cpp.i:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/zeekagent.cpp.i
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/zeekagent.cpp.i
.PHONY : src/zeekagent.cpp.i

src/zeekagent.s: src/zeekagent.cpp.s

.PHONY : src/zeekagent.s

# target to generate assembly for a file
src/zeekagent.cpp.s:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/zeekagent.cpp.s
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/zeekagent.cpp.s
.PHONY : src/zeekagent.cpp.s

src/zeekconnection.o: src/zeekconnection.cpp.o

.PHONY : src/zeekconnection.o

# target to build an object file
src/zeekconnection.cpp.o:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/zeekconnection.cpp.o
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/zeekconnection.cpp.o
.PHONY : src/zeekconnection.cpp.o

src/zeekconnection.i: src/zeekconnection.cpp.i

.PHONY : src/zeekconnection.i

# target to preprocess a source file
src/zeekconnection.cpp.i:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/zeekconnection.cpp.i
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/zeekconnection.cpp.i
.PHONY : src/zeekconnection.cpp.i

src/zeekconnection.s: src/zeekconnection.cpp.s

.PHONY : src/zeekconnection.s

# target to generate assembly for a file
src/zeekconnection.cpp.s:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/src/zeekconnection.cpp.s
	$(MAKE) -f CMakeFiles/zeek-agent.dir/build.make CMakeFiles/zeek-agent.dir/src/zeekconnection.cpp.s
.PHONY : src/zeekconnection.cpp.s

tests/main.o: tests/main.cpp.o

.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i

.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s

.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

tests/zeekconnection.o: tests/zeekconnection.cpp.o

.PHONY : tests/zeekconnection.o

# target to build an object file
tests/zeekconnection.cpp.o:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/tests/zeekconnection.cpp.o
.PHONY : tests/zeekconnection.cpp.o

tests/zeekconnection.i: tests/zeekconnection.cpp.i

.PHONY : tests/zeekconnection.i

# target to preprocess a source file
tests/zeekconnection.cpp.i:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/tests/zeekconnection.cpp.i
.PHONY : tests/zeekconnection.cpp.i

tests/zeekconnection.s: tests/zeekconnection.cpp.s

.PHONY : tests/zeekconnection.s

# target to generate assembly for a file
tests/zeekconnection.cpp.s:
	$(MAKE) -f CMakeFiles/zeek-agent_tests.dir/build.make CMakeFiles/zeek-agent_tests.dir/tests/zeekconnection.cpp.s
.PHONY : tests/zeekconnection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... zeek_agent_tests"
	@echo "... zeek-agent_tests"
	@echo "... zeek-agent_tests_runner"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... zeek-agent"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... thirdparty_broker"
	@echo "... thirdparty_caf_openssl"
	@echo "... thirdparty_caf_io"
	@echo "... thirdparty_caf_core"
	@echo "... thirdparty_audit_libauparse"
	@echo "... thirdparty_audit_libaudit"
	@echo "... thirdparty_xxhash"
	@echo "... thirdparty_sqlite"
	@echo "... thirdparty_zlib"
	@echo "... thirdparty_openssl_builder"
	@echo "... zeek_utils"
	@echo "... zeek_database_tests_runner"
	@echo "... zeek_database_tests"
	@echo "... zeek_database"
	@echo "... zeek_logger"
	@echo "... zeek_service_manager"
	@echo "... zeek_configuration_tests_runner"
	@echo "... zeek_configuration_tests"
	@echo "... zeek_configuration"
	@echo "... zeek_audisp_tests_runner"
	@echo "... zeek_audisp_tests"
	@echo "... zeek_audisp"
	@echo "... zeek_audisp_tables_tests_runner"
	@echo "... zeek_audisp_tables_tests"
	@echo "... zeek_audisp_tables"
	@echo "... zeek_host_information_table"
	@echo "... src/configuration.o"
	@echo "... src/configuration.i"
	@echo "... src/configuration.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/queryscheduler.o"
	@echo "... src/queryscheduler.i"
	@echo "... src/queryscheduler.s"
	@echo "... src/uniquexxh64state.o"
	@echo "... src/uniquexxh64state.i"
	@echo "... src/uniquexxh64state.s"
	@echo "... src/zeekagent.o"
	@echo "... src/zeekagent.i"
	@echo "... src/zeekagent.s"
	@echo "... src/zeekconnection.o"
	@echo "... src/zeekconnection.i"
	@echo "... src/zeekconnection.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
	@echo "... tests/zeekconnection.o"
	@echo "... tests/zeekconnection.i"
	@echo "... tests/zeekconnection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

